version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
    volumes:
      - ../database:/var/lib/mysql
      - ../sql_init:/sql_init
    env_file:
      - .env
    networks:
      - pass-app-net

  

  flask:
    build: .
    container_name: flask
    depends_on:
      - db
    volumes:
      - ../app:/app
    expose:
      - "5000"
    restart: always
    env_file:
      - .env
    command: >
      python3 app.py
    networks:
      - pass-app-net

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - flask
    restart: always
    ports:
      - "443:443"
      - "80:80" 
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/ssl:/etc/ssl/
      - ../nginx/www:/var/www/html
    networks:
      - pass-app-net
networks:
  pass-app-net: